### get orders period
GET localhost:8080/api/order/customer/orders?start=2024-08-25&end=2024-09-30&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJxaWpTQWpEdVVGUVZ5WmwxZDErbGdRPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNjAzMjkwMiwiZXhwIjoxNzI2MTE5MzAyfQ.H5B5SM1xJCLJv1oxaXOzHRryfutsXIVWlph8VZ_QhtspNA3trZpjziGrZJQQEuw4F7zmJGZS1IYZD2BvWkN93Q

### get order detail
GET localhost:8080/api/order/customer/order?id=20020
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJxaWpTQWpEdVVGUVZ5WmwxZDErbGdRPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNjAzMjkwMiwiZXhwIjoxNzI2MTE5MzAyfQ.H5B5SM1xJCLJv1oxaXOzHRryfutsXIVWlph8VZ_QhtspNA3trZpjziGrZJQQEuw4F7zmJGZS1IYZD2BvWkN93Q

### cancel order
DELETE localhost:8080/api/order/customer/order/cancel?id=20020
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJxaWpTQWpEdVVGUVZ5WmwxZDErbGdRPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNjAzMjkwMiwiZXhwIjoxNzI2MTE5MzAyfQ.H5B5SM1xJCLJv1oxaXOzHRryfutsXIVWlph8VZ_QhtspNA3trZpjziGrZJQQEuw4F7zmJGZS1IYZD2BvWkN93Q
