### cart 주문
POST localhost:8080/api/store/cart/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJxaWpTQWpEdVVGUVZ5WmwxZDErbGdRPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNjgzMDU0NiwiZXhwIjoxNzI2OTE2OTQ2fQ.oYVEV2KANKgZ9MNPmAWl7bvxyk_Fgo3MAxK6WWKsXcvIw9VUFDHLTBVNBJXOFX2F9oyl0RdSa35wy8jhKZmiPw

{
  "items": [
    {
      "id": 6,
      "storeId": 2,
      "sellerId": 1,
      "storeName": "달달구리해닮",
      "name": "샹티크림끌레오르",
      "options": [
        {
          "id": 11,
          "name": "얼그레이샹티크림 끌레오르",
          "quantity": 2,
          "price": 26000
        },
        {
          "id": 12,
          "name": "블루베리샹티크림 끌레오르",
          "quantity": 2,
          "price": 26000
        }
      ]
    }
  ],
  "messages": [],
  "totalPrice": 212000
}