pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
        repository = "hjuuujh/member-api"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
//        stage('build') {
//            steps {
//                echo 'Clone'
//                sh 'ls -al'
//                sh 'chmod +x gradlew'
//                sh './gradlew member-api:build'
//
//            }
//        }
//
//        stage('docker hub push') {
//            steps {
//                dir('member-api') {
//                    script {
//                        sh 'ls -al'
//                        dockerImage = docker.build "hjuuujh/member-api"
//                        docker.withRegistry('', 'dockerhub') {
//                            dockerImage.push("1.0")
//                        }
//                    }
//                }
//            }
//        }

        stage('Build image') {
            steps {
                sshagent(credentials: ['ssh']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@13.209.81.60 'ls -al'
                       '''
                }
            }
        }
//
//          stage('Remove Previous image') {
//              steps {
//                  script {
//                      try {
//                          sh 'docker stop dessert-member-api'
//                      } catch (e) {
//                          echo 'fail to stop and remove container'
//                      }
//                  }
//              }
//          }
//
//          stage('Run New image') {
//              steps {d
//                  sh 'docker-compose up --build -d dessert-member-api'
//                  echo 'Run New member image'
//              }
//          }
    }
}