### cart 주문
POST dessert-alb-166253251.ap-northeast-2.elb.amazonaws.com:8080/api/store/cart/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyNjc1MTA2MCwiZXhwIjoxNzI2ODM3NDYwfQ.ljPFWS4gFF46WpA4YXlO4bODFSK1fJWqzrnWH57KQWQIwD7dK7KwK0TWjqwvmotYosivo1TKbb-pVQzeSy2ZhA

{
  "items": [
    {
      "id": 1,
      "storeId": 5,
      "sellerId": 1,
      "storeName": "디디얌",
      "name": "디디얌 마카롱 수제 뚱카롱 32종",
      "options": [
        {
          "id": 2,
          "name": "딸기바나나",
          "quantity": 2,
          "price": 2500
        }
      ]
    },
    {
      "id": 6,
      "storeId": 6,
      "sellerId": 1,
      "storeName": "달달구리해닮",
      "name": "샹티크림끌레오르",
      "options": [
        {
          "id": 12,
          "name": "블루베리샹티크림 끌레오르",
          "quantity": 2,
          "price": 26000
        },
        {
          "id": 11,
          "name": "얼그레이샹티크림 끌레오르",
          "quantity": 2,
          "price": 26000
        }
      ]
    }
  ],
  "messages": [],
  "totalPrice": 111500
}